# Generated by Django 5.2.4 on 2025-07-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_Finished',
            new_name='is_finished',
        ),
    ]
